#!/usr/bin/env bash
set -Eeuo pipefail

DATA_DIR="${DATA_DIR:-/var/kend/data}"
LOG_DIR="${LOG_DIR:-/var/kend/logs}"
CONF_DIR="${CONF_DIR:-/klaytn-docker-pkg/conf}"
CONF_FILE="${CONF_DIR}/kend.conf"
mkdir -p "$DATA_DIR" "$LOG_DIR" "$CONF_DIR"

if [[ ! -f "${DATA_DIR}/.initialized" ]]; then
  echo "Initializing Kaia EN data directory"
  if [[ -n "${SNAPSHOT:-}" ]]; then
    echo "Downloading Kaia chaindata snapshot: ${SNAPSHOT}"
    tmp="/tmp/kaia-snapshot.tar.gz"
    if command -v aria2c >/dev/null 2>&1; then
      aria2c -x 16 -s 16 -k 1M --file-allocation=none --allow-overwrite=true -d /tmp -o kaia-snapshot.tar.gz "${SNAPSHOT}"
    else
      curl -L "${SNAPSHOT}" -o "$tmp"
    fi
    echo "Extracting snapshot into ${DATA_DIR}"
    if command -v pigz >/dev/null 2>&1; then
      tar -I pigz --strip-components="${SNAPSHOT_STRIP_COMPONENTS:-0}" -xf "$tmp" -C "$DATA_DIR"
    else
      tar --strip-components="${SNAPSHOT_STRIP_COMPONENTS:-0}" -xzf "$tmp" -C "$DATA_DIR"
    fi
    rm -f "$tmp"
  else
    echo "No SNAPSHOT configured. Node will full-sync from genesis. This can take a long time."
  fi
  touch "${DATA_DIR}/.initialized"
else
  echo "Already initialized!"
fi

if [[ -z "${PUBLIC_IP:-}" ]]; then
  PUBLIC_IP="$(curl -fsS ifconfig.me/ip 2>/dev/null || true)"
fi

ADDITIONAL_FLAGS="${EXTRA_FLAGS:-}"
if [[ "${LIVE_PRUNING:-false}" == "true" ]]; then
  ADDITIONAL_FLAGS="${ADDITIONAL_FLAGS} --state.live-pruning --state.live-pruning-retention ${LIVE_PRUNING_RETENTION:-172800}"
fi
if [[ -n "${PUBLIC_IP:-}" ]]; then
  ADDITIONAL_FLAGS="${ADDITIONAL_FLAGS} --nat extip:${PUBLIC_IP}"
fi

cat > "$CONF_FILE" <<EOF_CONF
# Generated by kaia-docker. Changes here are overwritten on container start.
NETWORK="${NETWORK:-mainnet}"
DATA_DIR="${DATA_DIR}"
LOG_DIR="${LOG_DIR}"
PORT=${P2P_PORT:-32323}
SERVER_TYPE="fasthttp"
SYNCMODE="${SYNCMODE:-full}"
VERBOSITY=${VERBOSITY:-3}
MAXCONNECTIONS=${MAXCONNECTIONS:-100}
LDBCACHESIZE=${LDBCACHESIZE:-40960}

RPC_ENABLE=${RPC_ENABLE:-1}
RPC_ADDR="${RPC_ADDR:-0.0.0.0}"
RPC_PORT=${RPC_PORT:-8551}
RPC_API="${RPC_API:-eth,net,web3,klay,kaia,txpool,rpc}"
RPC_CORSDOMAIN="*"
RPC_VHOSTS="*"

WS_ENABLE=${WS_ENABLE:-1}
WS_ADDR="${WS_ADDR:-0.0.0.0}"
WS_PORT=${WS_PORT:-8552}
WS_API="${WS_API:-eth,net,web3,klay,kaia,txpool,rpc}"
WS_ORIGINS="*"

ADDITIONAL="${ADDITIONAL_FLAGS}"
EOF_CONF

chmod 0644 "$CONF_FILE"

echo "Configuration complete!"
echo "Starting Kaia endpoint node..."

kend start

touch "${LOG_DIR}/kend.out"
trap 'echo "Stopping Kaia endpoint node"; kend stop; exit 0' TERM INT
exec tail -F "${LOG_DIR}/kend.out"
